title: Instrumentation of a Three-Phase Transformer
description: "Instrumentation of a 10MVA 66kV/13.8kV power transformer for monitoring voltage, current, frequency, and power. Project completed as part of IECE 513 at the University at Albany."
theme: jekyll-theme-minimal
